---
#------------------#
#  install lazygit #
#------------------#

- name: Install lazygit (package)
  package:
    name: lazygit
    state: present
  become: yes
  tags: [common]
  when: >
    ansible_distribution in ["Archlinux"] or
    (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('25.04', '>='))

- name: Install lazygit (Ubuntu > 25.04)
  block:
    - name: Get latest lazygit release version
      uri:
        url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
        return_content: yes
      register: lazygit_release

    - name: set lazygit version
      set_fact:
        lazygit_version: "{{ lazygit_release.json.tag_name | regex_replace('^v', '')}}"

    - name: Download and extract lazygit
      unarchive:
        src: "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Install lazygit
      copy:
        src: /tmp/lazygit
        dest: /usr/local/bin/lazygit
        mode: "0755"
        remote_src: yes
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version ('25.04', '<')
  tags: [common]

- name: Install lazygit (Fedora)
  command: dnf copr enable -y dejan/lazygit
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:dejan:lazygit.repo
  become: yes
  tags: [common]
  when: ansible_distribution == "Fedora"
