---
- name: install git
  package:
    name: git
    state: present
  become: yes
  tags: [common]
#
# - name: Symlink git config
#   template:
#     src: "{{ ansible_env.HOME }}/.dotfiles/git/gitconfig.j2"
#     dest: "{{ ansible_env.HOME }}/.gitconfig"
#   tags: [common]

- name: create git config (template)
  template:
    src: gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
  tags: [common]
